# 
#$kernel_update = <<-KERNEL
#yum update kernel -y
#yum install kernel-devel -y
#shutdown -r
#KERNEL

#$script = <<-SCRIPT
#cp /etc/sysconfig/jenkins /etc/sysconfig/jenkins.$(date +"%Y-%m-%d_%H%M%S")
#sed -i 's/JENKINS_LISTEN_ADDRESS=.*/JENKINS_LISTEN_ADDRESS=\"0.0.0.0\"/' /etc/sysconfig/jenkins
#sed -i 's/JENKINS_AJP_LISTEN_ADDRESS=.*/JENKINS_AJP_LISTEN_ADDRESS=\"0.0.0.0\"/' /etc/sysconfig/jenkins
#service jenkins restart
#SCRIPT


Vagrant.configure("2") do |config|
  config.vm.box = "liatrio/jenkinsnexus"
  config.vm.box_version = "0.0.1"
  config.vbguest.auto_update = false
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8081, host: 8081
end


#  config.vm.provision "shell", inline: $kernel_update
#  config.vm.provision "shell", inline: $script

